services:
  postgresql:
    image: postgres:14.5-alpine
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=my_secret_password
      - POSTGRES_DB=naive
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgresql
    volumes:
      - static:/app/static
    ports:
      - "80:80"
    restart: always

volumes:
  static:
